apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: custom-notification
spec:
  text: "ğ’ğ€ğğƒğğğ— ğ‚ğ‹ğ”ğ’ğ“ğ„ğ‘"
  location: "BannerTop"
  backgroundColor: "#008000"
  color: "#FFFFFF"
