---
apiVersion: v1
kind: Namespace
metadata:
  name: book-import
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: book-import
  name: book-import
  namespace: book-import
spec:
  replicas: 2
  selector:
    matchLabels:
      name: book-import
  template:
    metadata:
      labels:
        name: book-import
    spec:
      containers:
      - image: quay.io/jpacker/hugo-nginx:latest
        name: book-import
        ports:
        - containerPort: 8080
          name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: book-import
  namespace: book-import
  labels:
    name: book-import
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: book-import
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: book-import
  namespace: book-import
  labels:
    name: book-import
spec:
  path: "/"
  to:
    kind: Service
    name: book-import
